### ISSUE TITLE
logQueryParams is not allowed

### ISSUE THREAD

**Issue by femans** [felixheck/laabr#104]
version 6.1.3
The option logQueryParams is disabled in the joi validation, and this makes it impossible to access the query parameters in the logger. (For my specific use case this makes the library unusable). It is easy enough to allow it, I think. Is there any specific reason why this has been disabled?

**Comment by felixheck** [comment]
Thanks for raising this issue, @femans. I quickly checked the code and the behaviour. I don't have a rule for `logQueryParams` defined but allowed explicitly "unknown" keys (such as in this case) in my validation for `hapi-pino` and `pino` options.

My guess: nest it inside the [`hapiPino`](https://github.com/felixheck/laabr/blob/master/docs/api.md#options) option and you are fine 👇

```js
await server.register({
  plugin: laabr,
  options: {
    hapiPino: { logQueryParams: true } 
  },
});
```

**Comment by femans** [comment]
Thanks @felixheck , for the swift answer. This indeed solves it! I am sorry I could not figure this out from the docs.

**Comment by felixheck** [comment]
All good, it’s quite a lot of options and easy to miss 😊 take care.
