### ISSUE TITLE
Default value "-" used on all falsy values instead of null / undefined

### ISSUE THREAD

**Issue by JSteunou** [felixheck/laabr#12]
For some data that could be integers, laabr logs `"-"` when the value is `0` because 0 is falsy, but `0` is the value to log.

The culprit is here https://github.com/felixheck/laabr/blob/master/src/logger.js#L41

**Comment by felixheck** [comment]
Hi!

And thanks for you me issue. 
that’s definitely a bug!

Would you mind creating a PR?😊 
I‘m currently on holiday. 

Otherwise I‘d handle the bug in a week. 
Thanks and cheers,

Felix

**Comment by felixheck** [comment]
@JSteunou is published as v3.1.5

Please give feedback :)

**Comment by JSteunou** [comment]
Just tried, works well. Thank you @felixheck !
