### ISSUE TITLE
Missing output of console.error when using override: true

### ISSUE THREAD

**Issue by jedrus2000** [felixheck/laabr#63]
Maybe it is me, not laabr but I've such issue - with laabr option `override: true`, when i.e. `TypeError` occurs and is caught, then reported with `console.error(error)`, I see only :

![image](https://user-images.githubusercontent.com/22714418/84574635-f92f6d00-ada7-11ea-82c4-3f87fd87b97b.png)

My stack is : 
```
Node v10 with Docker (node:10) : https://hub.docker.com/_/node/
hapi: 18.3.1,
laabr: 5.1.6
nodemon: 1.19.4
```

It started to annoy me more and more, and if error was happening, I had to start server with `override` set to false.
I looked into source code how `console` is implemented and found this : 

https://github.com/whatwg/console/blob/f276b49ad99c815a17a86b6c6cbc8ca842eb69d3/reference-implementation/Logger.js#L29

so I went to my :heart: laabr and this 
https://github.com/felixheck/laabr/blob/dfc458bd0690849d5be5e87a0ffb31aaceadaca2/src/utils.js#L59

I've changed into : 
```js
server.log(level, util.format(data))
```
( with `const util = require('util')` at source file beginning. )

So after this output looks that : 
![image](https://user-images.githubusercontent.com/22714418/84575500-bd97a180-adad-11ea-894b-98d8a392cad8.png)

My laabr `options` are : 
```
      options: {
        override: true, // Override several console logging methods
        formats: {
          log: ':time[iso], :level, :message',
          request: ':time[iso], :level, :message',
          response: ':time[iso], :level, :method, :url, :status, :payload, (:responseTime ms)',
          'request-error': ':time[iso], :level, :method, :url, :error[output.statusCode], :error, :error[stack]',
          onPostStart: ':time[iso], :level, :message',
          onPostStop: ':time[iso], :level, :message',
          uncaught: ':time[iso], :level, :error, :error[stack]'
        },
        pino: { level: 'info' },
        indent: 0,
        colored: true
    }
```

I must say that I cannot exactly reproduce it at my local Linux (using i.e. Node 14, latest laabr). So with my laabr options, using simple.js I've got this :

![image](https://user-images.githubusercontent.com/22714418/84575382-f08d6580-adac-11ea-9f2a-b18567256319.png)
 
With my modification in `laabr/src/utils.js` it looks like this : 
![image](https://user-images.githubusercontent.com/22714418/84575436-38ac8800-adad-11ea-96b1-5e5d0bff3513.png)

I think is more readable. @felixheck What do you think ?

**Comment by felixheck** [comment]
Thanks a ton for all the details and opening this issue!
I 100% with you, it’s definitely more readable.

Would you mind creating a PR?
More than happy to release it asap 😊
