### ISSUE TITLE
No colors in Docker container, even if colored is true - solved

### ISSUE THREAD

**Issue by jedrus2000** [felixheck/laabr#64]
I think my finding deserves note on main page, as probably most of us use Docker containers daily. 

When you see my screenshots from another issue : 
![image](https://user-images.githubusercontent.com/22714418/84575500-bd97a180-adad-11ea-894b-98d8a392cad8.png)

there are **no colors** even `laabr` `colored` option is set as `true`

It is [chalk](https://github.com/chalk/chalk) issue : https://github.com/chalk/chalk/issues/79

So putting : 
```
ENV FORCE_COLOR 1
```

in `Dockerfile` makes `colored: true` working in Docker container.

**Comment by felixheck** [comment]
Hi and thanks for this note — gonna add it to the README.
May I ask which laabr version you use? IIRC, chalk got replaced a while ago 😬
