### ISSUE TITLE
Problems when logging on AWS CloudWatch

### ISSUE THREAD

**Issue by bmxpiku** [felixheck/laabr#78]
Hello,
based on laabr and hapi-pino options I came up with this config:
```
export const laabrOptions = {
  formats: {
    log: ':time[iso], :level, :message',
    response: ':time[iso], :level, :method, :url, :status, :payload, bm-request-token: :req[request-token], (:responseTime ms)',
    'request-error': ':time[iso], :level, :method, :url, :payload, :error[output.statusCode], :error, :error[stack]',
    onPostStart: ':time[iso], :level, :message',
    onPostStop: ':time[iso], :level, :message',
  },
  indent: 0,
  colored: true,
  pino: {
    level: 'debug',
  },
  hapiPino: {
    prettyPrint: process.env.NODE_ENV !== 'production',
    mergeHapiLogData: true,
    ignorePaths: ['/healthcheck', '/favicon.ico'],
    ignoreFunc: (options, request) => request.path.startsWith('/assets'),
    redact: ['req.headers.authorization'],
    logPayload: true,
  },
};
```
Then I register it in hapi
`await server.register({ plugin: laabr, options: laabrOptions });`
and well -> locally it looks great 
`2020-12-11T10:22:33.467Z, info, GET, /healthcheck, 200, {}, request-token: xaxaxa, (5 ms)`

when we run this on aws cloudwatch what is see is this:
```
[90m2020-12-11T10:11:44.144Z[39m, [32minfo[39m, [32mGET[39m, /healthcheck, [32m200[39m, 
{}
, bm-request-token: -, (1 ms)
```

Note that id does log healthcheck path, would you have any idea what am I doing wrong here?

**Comment by felix-adnymics** [comment]
Hey @bmxpiku, thanks for using laabr and reporting your issue.
Seems like CloudWatch does not support coloured logs. Actually, I'm not sure why since [the used module](https://github.com/Marak/colors.js) states to auto-detect the terminal's colour support.

Removed the `colored: true` option should make it work, I'll investigate why the auto-detection does not work.

**Comment by felixheck** [comment]
what he says ☝️ 😉

**Comment by bmxpiku** [comment]
100% what he says :) 
Thanks for the help, it worked like a charm
