### ISSUE TITLE
joi as a peer dependency

### ISSUE THREAD

**Issue by rasgo-cc** [felixheck/laabr#84]
Any chance to have joi as a peer dependency?

I already had a (more recent) version of joi in my package and suddenly I started getting this error:
`Error: Cannot mix different versions of joi schemas`

Removing laabr fixed the issue but I think it would be good to have joi as a peer dependency to avoid this errors and let the developer to pick the version he wants to use.

**Comment by felixheck** [comment]
Hey! Sure, let's go it.
I'll be able to publish a new version within this week.
In case you wanna have right now, feel free to send a PR.

Take care,
Felix

**Comment by rasgo-cc** [comment]
Awesome @felixheck ! Somehow I got it working again. Removed laabr and added it back (the joi I had in my package was always there) and now both seem to co-exist fine. Not sure what happened or how both versions triggered the error above but still seems it could have been avoided if there was only one version installed.

**Comment by felixheck** [comment]
Hmm weird.
Better safe than sorry, let's make it a peer dep 😬
ETA Wednesday.
