### ISSUE TITLE
how to use laabr directly on another file?

### ISSUE THREAD

**Issue by hbinduni** [felixheck/laabr#86]
hi, when using `pino`, i can use it directly in another file as below:
```
import pino from 'pino';
export const logger = pino({level: 'info'});
```

how can i do the same with `laabr`?

**Comment by felixheck** [comment]
Hey, that's unfortunately not possible without having the `req` or `server` object. As it's built on top of `hapi`'s logging system, it also inherits its limitations.

**Comment by hbinduni** [comment]
> Hey, that's unfortunately not possible without having the `req` or `server` object. As it's built on top of `hapi`'s logging system, it also inherits its limitations.

thank you for your confirmation
