### ISSUE TITLE
How to apply custom format with color?

### ISSUE THREAD

**Issue by hbinduni** [felixheck/laabr#87]
I have custom format option like this:
```
formats: {
    log: ':time[iso], :level: :message'
}
```

how i can apply color with custom format? like, how to change time color from grey to red?

**Comment by felixheck** [comment]
You can override these tokens (e.g. `:time`):

```js
laabr.token('time', (data, colors, field) => {
  const date = new Date(data.time)
  let ts = data.time

  switch (field) {
    case 'iso':
      ts = date.toISOString()
      break
    case 'utc':
      ts = date.toUTCString()
      break
  }

  return colors.red(ts)
})
```

👉  https://github.com/felixheck/laabr/blob/master/docs/api.md#laabrtokenstring-name-function-callback

**Comment by hbinduni** [comment]
@felixheck  Thank you. You really help
