### ISSUE TITLE
Is it possible to limit the payload tag?

### ISSUE THREAD

**Issue by perbu** [felixheck/laabr#88]
Hi.
I'm curious if is possible to limit the size of logged payload? I typically wanna log the payload but when I get these chonkers I wanna limit the payload to some arbitrary number. Is that possible?

**Comment by felixheck** [comment]
Hey 👋 

Not out of the box but you can define a custom [token](https://github.com/felixheck/laabr/blob/master/docs/tokens-formats-presets.md#tokens) or override an existing one:
https://github.com/felixheck/laabr/blob/master/docs/api.md#laabrtokenstring-name-function-callback

This allows you to define your own limits 😊 Hope it helps!

**Comment by perbu** [comment]
That is helpful! Thanks Felix!
