### ISSUE TITLE
Register using Glue

### ISSUE THREAD

**Issue by axpro** [felixheck/laabr#9]
I can't seem to make it work when I compose my server using [Glue](https://github.com/hapijs/glue) from a config json.

I get `Error: Invalid plugin options` and `"register" must be a Function` if I try to register using `"plugin": "laabr"` and `Cannot find module 'laabr.plugin'` if I try with `"plugin": "laabr.plugin"`

If I add `module.exports.register = plugin` to your plugin it works as expected. I guess Glue expects a `register` function.

**Comment by felixheck** [comment]
try:

```js
const laabr = require('laabr');

...

{
  plugin: laabr.plugin
}
```

without quotes. `laabr` is the module and the module exposes the plugin as `laabr.plugin` :)

**Comment by axpro** [comment]
I understand that but I use a json config file (external, unversioned file).

**Comment by felixheck** [comment]
Okaaaaay...so let's add another way which fits your needs :)

**Comment by felixheck** [comment]
published as `v3.1.0` — see docs and examples.
Please give some feedback if it works!

**Comment by axpro** [comment]
I'm not on hapi 17 yet but I checked the code and it should work as expected. Thank you very much for the support 👍

**Comment by felixheck** [comment]
If you wanna a hapi v16 supporting version, just fire a PR and I'll publish it as 2.x.x :)

**Comment by axpro** [comment]
Thank you but I plan to upgrade all my servers to 17 after the holidays and this is just another impulse to do just that :)

**Comment by felixheck** [comment]
If there is any further input, just open an issue or PR. Let's make this plugin awesome ;-)
